### ISSUE TITLE
Too long words on posts

### ISSUE THREAD

**Issue by jiurate** [limzykenneth/ualfutures-frontend#20]
Can we do something about when long words appear on posts, ie ‘CSSReference.io’? Also, ‘Collaboration’ (it also doesn’t seem centered) (see screengrabs)

<img width="488" alt="screen shot 2016-12-06 at 07 47 45" src="https://cloud.githubusercontent.com/assets/13275142/20960176/0ac98488-bc57-11e6-8805-ce3340d3b695.png">
<img width="326" alt="screen shot 2016-12-06 at 07 46 47" src="https://cloud.githubusercontent.com/assets/13275142/20960177/0acc2f26-bc57-11e6-977d-9010ded7f2a0.png">

**Comment by limzykenneth** [comment]
Three things we can potentially do here:

1. We can reduce the size of the text so that they fit. Currently they are all the same size regardless of screen size. It might not solve cases where the name is one word and too long though.
2. We can make the long words automatically break into two but what might happen in some case is that for example CSSReference.io will be broken into two lines like "CSSRefere" and "nce.io".
3. The title can have a soft hyphen `&shy;` where ideally it would be broken if necessary but that needs to be added manually and would introduce a hyphen where the word breaks.

A combination of 1 and 2/3 should probably be used. Not sure which is the best way to do it though.

**Comment by jiurate** [comment]
I think the combination of 1&3 could be the best option.

**Comment by limzykenneth** [comment]
Solving this along with responsive design

**Comment by limzykenneth** [comment]
Deployed
